#cloud-config

# System settings
hostname: debian-vm
fqdn: debian-vm.localdomain
timezone: Europe/Rome

# Enable SSH password authentication
ssh_pwauth: true
disable_root: false

# Users
users:
  - name: debian-user
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: [sudo, users]
    shell: /bin/bash
    lock_passwd: false
    passwd: <hashed_pass>
    ssh_authorized_keys:
      - <public_cert>

# Packages to install
packages:
  - openssh-server
  - sudo
  - curl
  - wget
  - vim
  - net-tools
  - avahi-daemon
  - htop

# Commands to run after boot
runcmd:
  - systemctl enable ssh
  - systemctl start ssh
  - systemctl enable systemd-networkd
  - systemctl start systemd-networkd

# Final message
final_message: "Cloud-init setup complete! SSH ready on port 22."